// eslint-disable-next-line import/no-anonymous-default-export
export default {
  app_name: "طلا و جواهری ریحان",
  app_description: "  شعاری درمورد گالری",
  neckband: "گردنبند",
  please_enter_your_verification_code: "لطفا کد ارسال شده به شماره",
  enter: "را وارد نمایید",
  home: "خانه",
  about_us: "درباره ما",
  faq: "سوالات متدوال",
  sort_by: "مرتب سازی بر اساس:",
  cart: "سبد خرید",
  products: "محصولات",
  category: "دسته بندی",
  categories: "دسته بندی",
  detail_product: "جزییات محصول",
  detail_order: "جزییات فاکتور",
  description: "توضیحات",
  mobile_number: "شماره همراه",
  address: "آدرس",
  debt: "بدهکاری",
  continue: "ادامه",
  no_description: "بدون توضیحات",
  signup: "ثبت نام",
  login: "ورود",
  firstName: "نام",
  lastName: "نام خانوادگی",
  remove: "حذف",
  code: "کد",
  weight: "وزن",
  gold: "طلا",
  diamond: "برلیان",
  count: "تعداد",
  number: "عدد",
  gram: "گرم",
  all: "همه",
  profile: "نمایه",
  logout: "خروج",
  i_know: "متوجه شدم!",
  orders: "فاکتورها",
  orders_description: "فاکتورها موجود خود را مشاهده کنید",
  logout_description: "خروج از حساب کاربری",
  about_us_description: "درباره ما اینجا بخوانید",
  faq_description: " سوالات متدوال  را اینجا بخوانید",
  available: "موجود",
  unAvailable: "ناموجود",
  pending: "در حال بررسی",
  accept: "قبول سفارش",
  reject: "رد سفارش",
  complete: "سفارش تحویل داده شده است",
  view_detail: "مشاهده جزییات",
  view: "مشاهده ",
  edit: "ویرایش ",
  send_verification_code_sucessfully: "کد تایید با موفقیت ارسال شد",
  register_your_cart_successfully: "سفارش شما با موفقیت ثبت شد",
  this_field_is_required: "این فیلد اجباری است",
  choose_your_file: " فایل خود را انتخاب نمایید (png،jpg,jpeg) ",
  please_enter_your_mobile_number_correctly:
    "لطفا شماره همراه خود را به درستی وارد نمایید",
  code_max_is_four_numbers: "کد وارد شده باید ۴رقمی باشد",
  terms_and_condition: "قوانین و مقررات",
  disable_user_description:
    "کاربر گرامی  پس از تایید پشتیبانی حساب کاربری شما فعال خواهد شد و میتوانید از وبسایت استفاده کنید. با تشکر",
  add_to_cart: "اضافه کردن به سبد خرید",
  add: "افزودن",
  fee: "اجرت",
  percent: "درصد",
  add_order: "ثبت  سفارش",
  lorem:
    "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
  // pwa_app: "نسخه پیشرو پخش پایه یزدانی را به دسکتاپ یا موبایل خود اضافه کنید",
  without_update: "بدون نیاز به به‌روزرسانی",
  open_in_chrome: "در مرورگر کروم آدرس را باز کنید",
  open_from_menu: "را ابتدا از قسمت منو انتخاب کنید",
  choose_add_home: "گزینه Add to Home Screen را انتخاب کنید",
  choose_from_window: "را از پنجره باز شده انتخاب کنید",
  choose_menu_addressbar: "گزینه را از نوار آدرس انتخاب کنید",
  install_option: "را از پنجره باز شده انتخاب کنید",
  // show_app_in_homescreen:
  // "اپ پیشرو  پخش پایه یزدانی  را می‌توانید در دسکتاپ یا پوشه برنامه‌ها مشاهده کنید",
  // open_in_safari: "در مرورگر سافاری آدرس را باز کنید",
  open_share_from_down: "را ابتدا از قسمت پایین انتخاب کنید",
  material: "جنس",
};
